import { Mulish } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import DrawerAppBar from "./components/commons/NavBar";
import Footer from "./components/commons/footer";

const inter = Mulish({
  weight:"500",
  subsets: ["latin"] 
});

export const metadata: Metadata = {
  title: "My project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DrawerAppBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
